baseurl = "/"
languageCode = "en-us"
title = "JMW"
author = "Jenny Wang"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "JMW"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Reading"
    url  = "/reading/reading_landing_page"
[[menu.main]]
    name = "Writing"
    url  = "/writing/writing_landing_page"
[[menu.main]]
    name = "Art" 
    url  = "/art/art_landing_page"

